### ISSUE TITLE
COHORT parameter not applied correctly to ICEES PCD instance

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#228] opened 2022-03-11 00:04 UTC
This issue is to report that the COHORT parameter is not being applied correctly to ICEES PCD functionalities.

For instance, this query:
```

curl -X 'POST' \
  'https://icees-pcd.renci.org/patient/cohort/COHORT%3A3/associations_to_all_features' \
  -H 'accept: text/tabular' \
  -H 'Content-Type: application/json' \
  -d '{
  "feature": {
    "TotalEDInpatientVisits": {
      "operator": "=",
      "value": "0"
    }
  },
  "maximum_p_value": 1,
  "correction": {
    "method": "bonferroni"
  }
}'

```
Is returning this response:

![image](https://user-images.githubusercontent.com/26254388/157775652-d5385075-c626-464e-abbf-fd31528296c4.png)

Yet COHORT:3 contains N=163 patients:

![image](https://user-images.githubusercontent.com/26254388/157775823-f051ea47-8f1f-40ad-a050-724227b843be.png)

I ran a similar test on the ICEES Asthma instance, which appeared to handle the COHORT parameter correctly.
```
```

**Comment by karafecho** [comment] 2022-03-14 18:33
I retested this, given the issues with the COVID dev deployment. I confirmed the error with COHORT:3 (N=163), but the functionality appears to work with COHORT:2 (N=4840).

**Comment by karafecho** [comment] 2022-03-14 20:26
Same issue arose with COHORT:7 (N=40), which returns results for N=4840 (COHORT:2?).

**Comment by hyi** [comment] 2022-03-29 16:53
@karafecho I believe this issue can be closed since this issue was caused by redis database cache out of sync which has already been covered by this issue #230.

**Comment by hyi** [comment] 2023-03-01 15:10
Closing the issue as @karafecho indicated above that this issue can be closed.

**Closed by hyi** 2023-03-01 15:10 UTC
